<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Game [
<!ELEMENT Game (QuestionLine*)>
<!ELEMENT QuestionLine ((Question, CorrectAnswer, IncorrectAnswer+)|(Question, IncorrectAnswer+, CorrectAnswer))>
<!ELEMENT Question (#PCDATA)>
<!ELEMENT CorrectAnswer (#PCDATA)>
<!ELEMENT IncorrectAnswer (#PCDATA)>
<!ATTLIST QuestionLine id CDATA #REQUIRED>
]>
<Game>
  <QuestionLine id="1"> <!--ID must be unique and incremental-->
    <Question>¿Cual es la ciudad mas poblada del Mundo?</Question> <!--Question always first-->
    <IncorrectAnswer>Shangai</IncorrectAnswer><!-- Order of next elements doesn't care-->
    <CorrectAnswer>Tokio</CorrectAnswer>
    <IncorrectAnswer>Madrid</IncorrectAnswer>
    <IncorrectAnswer>Nueva York</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="2">
    <Question>¿En que equipo juega Lionel Messi?</Question>
    <IncorrectAnswer>Real Madrid</IncorrectAnswer>
    <IncorrectAnswer>Real Sociedad</IncorrectAnswer>
    <IncorrectAnswer>AC Milan</IncorrectAnswer>
    <CorrectAnswer>FC Barcelona</CorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="3">
    <Question>¿Cuantas Veces parpadea una persona por semana de media?</Question>
    <CorrectAnswer>25.000 veces por semana</CorrectAnswer>
    <IncorrectAnswer>40.000 veces por semana</IncorrectAnswer>
    <IncorrectAnswer>100.000 veces por semana</IncorrectAnswer>
    <IncorrectAnswer>5.000 veces por semana</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="4">
    <Question>¿Cuantas Veces parpadea una persona por semana de media?</Question>
    <CorrectAnswer>25.000 veces por semana</CorrectAnswer>
    <IncorrectAnswer>40.000 veces por semana</IncorrectAnswer>
    <IncorrectAnswer>100.000 veces por semana</IncorrectAnswer>
    <IncorrectAnswer>5.000 veces por semana</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="5">
    <Question>¿Donde se originaron los Juegos Olimpicos?</Question>
    <CorrectAnswer>Grecia</CorrectAnswer>
    <IncorrectAnswer>Troya</IncorrectAnswer>
    <IncorrectAnswer>Roma</IncorrectAnswer>
    <IncorrectAnswer>Pekin</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="6">
    <Question>¿Cual es el pais mas grande del mundo?</Question>
    <CorrectAnswer>Rusia</CorrectAnswer>
    <IncorrectAnswer>China</IncorrectAnswer>
    <IncorrectAnswer>Estados Unidos</IncorrectAnswer>
    <IncorrectAnswer>Australia</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="7">
    <Question>¿Cual es el animal terrestre mas rapido del mundo?</Question>
    <CorrectAnswer>Guepardo</CorrectAnswer>
    <IncorrectAnswer>Puma</IncorrectAnswer>
    <IncorrectAnswer>Leon</IncorrectAnswer>
    <IncorrectAnswer>Elefante</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="8">
    <Question>¿Cuantos dientes tiene una persona adulta?</Question>
    <CorrectAnswer>32</CorrectAnswer>
    <IncorrectAnswer>36</IncorrectAnswer>
    <IncorrectAnswer>40</IncorrectAnswer>
    <IncorrectAnswer>29</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="9">
    <Question>¿Como se llama el restaurante en el que trabaja bob esponja?</Question>
    <CorrectAnswer>Crustaceo Crugiente</CorrectAnswer>
    <IncorrectAnswer>Krusty Burger</IncorrectAnswer>
    <IncorrectAnswer>Cangrejo Crugiente</IncorrectAnswer>
    <IncorrectAnswer>Cangrejo Burger</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="10">
    <Question>¿Cual fue el primer Pokemon que capturo Ash Ketchum en la serie?</Question>
    <CorrectAnswer>Caterpie</CorrectAnswer>
    <IncorrectAnswer>Pikachu</IncorrectAnswer>
    <IncorrectAnswer>Pidgey</IncorrectAnswer>
    <IncorrectAnswer>Charmander</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="11">
    <Question>¿Cuantas Bolas de Dragon existian en la serie?</Question>
    <CorrectAnswer>7</CorrectAnswer>
    <IncorrectAnswer>8</IncorrectAnswer>
    <IncorrectAnswer>9</IncorrectAnswer>
    <IncorrectAnswer>6</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="12">
    <Question>La ciencia que estudia a los animales en todos sus aspectos se denomina:</Question>
    <CorrectAnswer>Zoología</CorrectAnswer>
    <IncorrectAnswer>Botánica</IncorrectAnswer>
    <IncorrectAnswer>Ecología</IncorrectAnswer>
    <IncorrectAnswer>Microbiología</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="13">
    <Question>¿A qué provincia pertenece Algeciras?</Question>
    <CorrectAnswer>Cadiz</CorrectAnswer>
    <IncorrectAnswer>Granada</IncorrectAnswer>
    <IncorrectAnswer>Huelva</IncorrectAnswer>
    <IncorrectAnswer>Badajoz</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="14">
    <Question>¿Cómo continúa el siguiente refrán: "Más vale lo malo conocido que..."?</Question>
    <CorrectAnswer>Lo bueno por conocer</CorrectAnswer>
    <IncorrectAnswer>Lo peor conocido</IncorrectAnswer>
    <IncorrectAnswer>Lo malo conocido en el pasado</IncorrectAnswer>
    <IncorrectAnswer>Lo peor por conocer</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="15">
    <Question>¿Cuántos pulmones tiene el cuerpo humano?</Question>
    <CorrectAnswer>2</CorrectAnswer>
    <IncorrectAnswer>1</IncorrectAnswer>
    <IncorrectAnswer>0</IncorrectAnswer>
    <IncorrectAnswer>3</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="16">
    <Question>El movimiento de traslación consiste en:</Question>
    <CorrectAnswer>La rotación de la Tierra alrededor del Sol</CorrectAnswer>
    <IncorrectAnswer>La rotación del Sol alrededor de su propio eje de rotación</IncorrectAnswer>
    <IncorrectAnswer>La rotación de la Tierra alrededor de su propio eje de rotación</IncorrectAnswer>
    <IncorrectAnswer>La rotación del Sol alrededor de un eje externo</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="17">
    <Question>Por la comunidad autónoma de Andalucía pasa el río:</Question>
    <CorrectAnswer>Guadiana</CorrectAnswer>
    <IncorrectAnswer>Duero</IncorrectAnswer>
    <IncorrectAnswer>Tajo</IncorrectAnswer>
    <IncorrectAnswer>Ebro</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="18">
    <Question>¿Cómo se llaman los animales que sólo comen plantas?</Question>
    <CorrectAnswer>Herbívoros</CorrectAnswer>
    <IncorrectAnswer>Omnívoros</IncorrectAnswer>
    <IncorrectAnswer>Vegetarianos</IncorrectAnswer>
    <IncorrectAnswer>Carnivoros</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="19">
    <Question>¿Cuántos lados tiene un hexágono?</Question>
    <CorrectAnswer>6</CorrectAnswer>
    <IncorrectAnswer>8</IncorrectAnswer>
    <IncorrectAnswer>7</IncorrectAnswer>
    <IncorrectAnswer>5</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="20">
    <Question>¿Qué tipo de ganadería se ocupa de las ovejas?</Question>
    <CorrectAnswer>Ovina</CorrectAnswer>
    <IncorrectAnswer>Bovina</IncorrectAnswer>
    <IncorrectAnswer>Porcina</IncorrectAnswer>
    <IncorrectAnswer>Ovícula</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="21">
    <Question>¿Cuál de las siguientes palabras no es un verbo?</Question>
    <CorrectAnswer>Lugar</CorrectAnswer>
    <IncorrectAnswer>Mandar</IncorrectAnswer>
    <IncorrectAnswer>Tratar</IncorrectAnswer>
    <IncorrectAnswer>Comprar</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="22">
    <Question>¿Cómo denominaron los romanos al Mar Mediterráneo?</Question>
    <CorrectAnswer>Mare Nostrum</CorrectAnswer>
    <IncorrectAnswer>Mare Clusum</IncorrectAnswer>
    <IncorrectAnswer>Mare Propium</IncorrectAnswer>
    <IncorrectAnswer>Mere Opium</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="23">
    <Question>¿En qué isla canaria se encuentra el parque nacional de Timanfaya?</Question>
    <CorrectAnswer>Lanzarote</CorrectAnswer>
    <IncorrectAnswer>Tenerife</IncorrectAnswer>
    <IncorrectAnswer>Hierro</IncorrectAnswer>
    <IncorrectAnswer>Fuerteventura</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="24">
    <Question>¿Cuál de las siguientes palabras es un sustantivo?</Question>
    <CorrectAnswer>Manjar</CorrectAnswer>
    <IncorrectAnswer>Completar</IncorrectAnswer>
    <IncorrectAnswer>Cenar</IncorrectAnswer>
    <IncorrectAnswer>Comer</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="25">
    <Question>Con la llegada al trono de Carlos I, se instaura en España la monarquía de los Austrias, ¿qué nombre recibía la rama hispana de la casa europea?</Question>
    <CorrectAnswer>Habsburgo</CorrectAnswer>
    <IncorrectAnswer>Saboya</IncorrectAnswer>
    <IncorrectAnswer>Borbón</IncorrectAnswer>
    <IncorrectAnswer>Estuardo</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="26">
    <Question>El orden de los elementos en la tabla periódica tiene en cuenta:</Question>
    <CorrectAnswer>El peso atómico</CorrectAnswer>
    <IncorrectAnswer>El tamaño</IncorrectAnswer>
    <IncorrectAnswer>El color</IncorrectAnswer>
    <IncorrectAnswer>La temperatura</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="27">
    <Question>¿Con qué colores suele tener problemas un daltónico?</Question>
    <CorrectAnswer>Rojo y verde</CorrectAnswer>
    <IncorrectAnswer>Rojo y amarillo</IncorrectAnswer>
    <IncorrectAnswer>Verde y amarillo</IncorrectAnswer>
    <IncorrectAnswer>Amarillo y azul</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="28">
    <Question>¿Quiénes se enfrentaron en la Guerra de los Cien Años?</Question>
    <CorrectAnswer>Francia e Inglaterra</CorrectAnswer>
    <IncorrectAnswer>Francia e Italia</IncorrectAnswer>
    <IncorrectAnswer>Alemania e Inglaterra</IncorrectAnswer>
    <IncorrectAnswer>Francia y Alemania</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="29">
    <Question>¿Quién fue el primer emperador de Roma?</Question>
    <CorrectAnswer>Augusto</CorrectAnswer>
    <IncorrectAnswer>Nerón</IncorrectAnswer>
    <IncorrectAnswer>Trajano</IncorrectAnswer>
    <IncorrectAnswer>Julio César</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="30">
    <Question>¿Con qué otro nombre se denomina al hexaedro?</Question>
    <CorrectAnswer>Cubo</CorrectAnswer>
    <IncorrectAnswer>Cono</IncorrectAnswer>
    <IncorrectAnswer>Pirámide</IncorrectAnswer>
    <IncorrectAnswer>Esfera</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="31">
    <Question>En un septenio, ¿cuántos años trascurren?</Question>
    <CorrectAnswer>7</CorrectAnswer>
    <IncorrectAnswer>6</IncorrectAnswer>
    <IncorrectAnswer>5</IncorrectAnswer>
    <IncorrectAnswer>10</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="32">
    <Question>"El libro de la Selva" es una obra de:</Question>
    <CorrectAnswer>Rudyard Kipling</CorrectAnswer>
    <IncorrectAnswer>Stevenson</IncorrectAnswer>
    <IncorrectAnswer>Flaubert</IncorrectAnswer>
    <IncorrectAnswer>Zola</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="33">
    <Question>¿Qué significan las siglas ADN?</Question>
    <CorrectAnswer>Ácido Desoxirribonucleico</CorrectAnswer>
    <IncorrectAnswer>Ácido Ribonucleico</IncorrectAnswer>
    <IncorrectAnswer>Ácido Ascórbico</IncorrectAnswer>
    <IncorrectAnswer>Ácido Cítrico</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="34">
    <Question>¿Cómo fue llamado el periodo histórico comprendido entre la segunda mitad del siglo XVIII y principios del XIX en el que se llevaron a cabo transformaciones socioeconómicas, tecnológicas y culturales de la historia de la humanidad?</Question>
    <CorrectAnswer>Revolución Industrial</CorrectAnswer>
    <IncorrectAnswer>Revolución Europea</IncorrectAnswer>
    <IncorrectAnswer>Revolución Inglesa</IncorrectAnswer>
    <IncorrectAnswer>Revolución Francesa</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="35">
    <Question>¿En qué zona de la Península Ibérica se instalaron los pueblos celtas?</Question>
    <CorrectAnswer>Al Noroeste</CorrectAnswer>
    <IncorrectAnswer>Al Sur</IncorrectAnswer>
    <IncorrectAnswer>Al Noreste</IncorrectAnswer>
    <IncorrectAnswer>Al Sureste</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="36">
    <Question>¿Cuál de las siguientes palabras es un sustantivo?</Question>
    <CorrectAnswer>Cordón</CorrectAnswer>
    <IncorrectAnswer>Partir</IncorrectAnswer>
    <IncorrectAnswer>Acordar</IncorrectAnswer>
    <IncorrectAnswer>Mentir</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="37">
    <Question>¿Dónde se encuentran los montes Apeninos?</Question>
    <CorrectAnswer>Italia</CorrectAnswer>
    <IncorrectAnswer>Francia</IncorrectAnswer>
    <IncorrectAnswer>Turquía</IncorrectAnswer>
    <IncorrectAnswer>Grecia</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="38">
    <Question>De las siguientes palabras señala cuál de ellas está escrita correctamente:</Question>
    <CorrectAnswer>Divergencia</CorrectAnswer>
    <IncorrectAnswer>Dibergencia</IncorrectAnswer>
    <IncorrectAnswer>Diberjencia</IncorrectAnswer>
    <IncorrectAnswer>Diverjencia</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="39">
    <Question>¿Cuál de los siguientes tiburones tiene mayor tamaño?</Question>
    <CorrectAnswer>El tiburón ballena</CorrectAnswer>
    <IncorrectAnswer>El tiburón clavo</IncorrectAnswer>
    <IncorrectAnswer>El tiburón blanco</IncorrectAnswer>
    <IncorrectAnswer>El tiburón negro</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="40">
    <Question>¿Cuál de las siguientes es considerada la mayor batalla marítima de la historia?</Question>
    <CorrectAnswer>Batalla de Trafalgar</CorrectAnswer>
    <IncorrectAnswer>Batalla del Ebro</IncorrectAnswer>
    <IncorrectAnswer>Batalla de Lepanto</IncorrectAnswer>
    <IncorrectAnswer>Batalla de Waterloo</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="41">
    <Question>¿De los siguientes cuál es el planeta más caliente?</Question>
    <CorrectAnswer>Venus</CorrectAnswer>
    <IncorrectAnswer>Mercurio</IncorrectAnswer>
    <IncorrectAnswer>Júpiter</IncorrectAnswer>
    <IncorrectAnswer>Marte</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="42">
    <Question>¿Con qué nombre fue denominada la Península Ibérica durante la dominación musulmana?</Question>
    <CorrectAnswer>Al Ándalus</CorrectAnswer>
    <IncorrectAnswer>Bética</IncorrectAnswer>
    <IncorrectAnswer>Iberia</IncorrectAnswer>
    <IncorrectAnswer>Península Bética</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="43">
    <Question>La capital de Irlanda es:</Question>
    <CorrectAnswer>Dublín</CorrectAnswer>
    <IncorrectAnswer>Budapest</IncorrectAnswer>
    <IncorrectAnswer>Atenas</IncorrectAnswer>
    <IncorrectAnswer>Berlín</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="44">
    <Question>¿En qué año comenzó la invasión musulmana en la Península Ibérica?</Question>
    <CorrectAnswer>711</CorrectAnswer>
    <IncorrectAnswer>645</IncorrectAnswer>
    <IncorrectAnswer>729</IncorrectAnswer>
    <IncorrectAnswer>620</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="45">
    <Question>¿Cuál fue el sistema político predominante en la Europa occidental de la Edad Media?</Question>
    <CorrectAnswer>Feudalismo</CorrectAnswer>
    <IncorrectAnswer>Capitalismo</IncorrectAnswer>
    <IncorrectAnswer>Democracia</IncorrectAnswer>
    <IncorrectAnswer>Dictadura</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="46">
    <Question>¿Quién escribió "Es mejor ser rey de tu silencio que esclavo de tus palabras"?</Question>
    <CorrectAnswer>Shakespeare</CorrectAnswer>
    <IncorrectAnswer>Nietzsche</IncorrectAnswer>
    <IncorrectAnswer>Aristóteles</IncorrectAnswer>
    <IncorrectAnswer>Cicerón</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="47">
    <Question>¿Cuál es el elemento químico cuyo símbolo es Pb?</Question>
    <CorrectAnswer>Plomo</CorrectAnswer>
    <IncorrectAnswer>Praseodimio</IncorrectAnswer>
    <IncorrectAnswer>Platino</IncorrectAnswer>
    <IncorrectAnswer>Polonio</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="48">
    <Question>¿Cuál de las siguientes fuentes es una energía renovable?</Question>
    <CorrectAnswer>Biomasa</CorrectAnswer>
    <IncorrectAnswer>Energía nuclear</IncorrectAnswer>
    <IncorrectAnswer>Gas natural</IncorrectAnswer>
    <IncorrectAnswer>Petróleo</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="49">
    <Question>El gentilicio de la provincia de Navarra es:</Question>
    <CorrectAnswer>Navarro</CorrectAnswer>
    <IncorrectAnswer>Navarriense</IncorrectAnswer>
    <IncorrectAnswer>Navarrense</IncorrectAnswer>
    <IncorrectAnswer>Navarrico</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="50">
    <Question>¿Cómo se llamaban los poetas cantautores de la Edad Media?</Question>
    <CorrectAnswer>Trovador</CorrectAnswer>
    <IncorrectAnswer>Cancionero</IncorrectAnswer>
    <IncorrectAnswer>Juglar</IncorrectAnswer>
    <IncorrectAnswer>Cantante</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="51">
    <Question>¿Cuándo se inicia la Edad Contemporánea?</Question>
    <CorrectAnswer>1789</CorrectAnswer>
    <IncorrectAnswer>1879</IncorrectAnswer>
    <IncorrectAnswer>1788</IncorrectAnswer>
    <IncorrectAnswer>1978</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="52">
    <Question>¿A qué ejército pertenecían los centuriones?</Question>
    <CorrectAnswer>Romano</CorrectAnswer>
    <IncorrectAnswer>Ruso</IncorrectAnswer>
    <IncorrectAnswer>Griego</IncorrectAnswer>
    <IncorrectAnswer>Bizantino</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="53">
    <Question>El científico considerado el más importante del siglo XX fue:</Question>
    <CorrectAnswer>Albert Einstein</CorrectAnswer>
    <IncorrectAnswer>Galileo Galilei</IncorrectAnswer>
    <IncorrectAnswer>Isaac Newton</IncorrectAnswer>
    <IncorrectAnswer>Joseph-Louis de Lagrange</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="54">
    <Question>¿Cuál es la característica principal de la Edad de los Metales?:</Question>
    <CorrectAnswer>La aparición de los megalitos</CorrectAnswer>
    <IncorrectAnswer>La aparición de la escritura</IncorrectAnswer>
    <IncorrectAnswer>La aparición del fuego</IncorrectAnswer>
    <IncorrectAnswer>La sedentarización de la vida</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="55">
    <Question>¿Cómo se llaman las crías del águila?</Question>
    <CorrectAnswer>Aguilucho</CorrectAnswer>
    <IncorrectAnswer>Aguileño</IncorrectAnswer>
    <IncorrectAnswer>Aguiluño</IncorrectAnswer>
    <IncorrectAnswer>Águila</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="56">
    <Question>¿Dónde se encuentra la Basílica de San Pedro?</Question>
    <CorrectAnswer>Ciudad del Vaticano</CorrectAnswer>
    <IncorrectAnswer>Venecia</IncorrectAnswer>
    <IncorrectAnswer>Roma</IncorrectAnswer>
    <IncorrectAnswer>Florencia</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="57">
    <Question>¿Qué significó la revolución de 1848?</Question>
    <CorrectAnswer>La mejora de la condición de la clase obrera</CorrectAnswer>
    <IncorrectAnswer>La aspiración de mejoras de la clase obrera</IncorrectAnswer>
    <IncorrectAnswer>El fin del régimen feudal</IncorrectAnswer>
    <IncorrectAnswer>La eliminación de privilegios de la clase obrera</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="58">
    <Question>¿A qué equivale un metro?</Question>
    <CorrectAnswer>100 cm</CorrectAnswer>
    <IncorrectAnswer>100 dm</IncorrectAnswer>
    <IncorrectAnswer>100 mm</IncorrectAnswer>
    <IncorrectAnswer>10 m</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="59">
    <Question>¿Quién es la autora de "Harry Potter"?</Question>
    <CorrectAnswer>J. K. Rowling</CorrectAnswer>
    <IncorrectAnswer>F. R Harrison</IncorrectAnswer>
    <IncorrectAnswer>M. Williams</IncorrectAnswer>
    <IncorrectAnswer>J.L. Beaton</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="60">
    <Question>Cuatrimestre es la agrupación de:</Question>
    <CorrectAnswer>Cuatro meses</CorrectAnswer>
    <IncorrectAnswer>Dos meses</IncorrectAnswer>
    <IncorrectAnswer>Tres meses</IncorrectAnswer>
    <IncorrectAnswer>Seis meses</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="61">
    <Question>¿Cuál es la velocidad máxima de la luz en el vacío?</Question>
    <CorrectAnswer>300.000 km/s</CorrectAnswer>
    <IncorrectAnswer>500.000 km/s</IncorrectAnswer>
    <IncorrectAnswer>300.000 km/h</IncorrectAnswer>
    <IncorrectAnswer>500.000 km/h</IncorrectAnswer>
  </QuestionLine>
  
  <QuestionLine id="62">
    <Question>¿Qué planeta es famoso por los anillos que lo rodean?</Question>
    <CorrectAnswer>Saturno</CorrectAnswer>
    <IncorrectAnswer>Júpiter</IncorrectAnswer>
    <IncorrectAnswer>Urano</IncorrectAnswer>
    <IncorrectAnswer>Venus</IncorrectAnswer>
  </QuestionLine>
</Game>